version: "3.9"

services:
  frontend:
    build: ./src/react/aimsq-front
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ./src/react/aimsq-front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./src/python
    container_name: api-app
    ports:
      - "8000:8000"
    volumes:
      - ./src/python:/app
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

